[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false


[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false
